name: Judge

on:
  push:
    branches: ["step*"]

jobs:
  step1:
    if: ${{ github.ref == 'refs/heads/step1' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Judge
        id: judge
        run: result=$(diff -q template/base.txt work/answer.txt > /dev/null; echo $?) ; echo "has_diff=$result" >> $GITHUB_OUTPUT
      - run: |
          if [[ ${{ steps.judge.outputs.has_diff }} == 1 ]]; then \
            diff template/base.txt work/answer.txt >> $GITHUB_STEP_SUMMARY
          fi
      - run: exit ${{ steps.judge.outputs.has_diff }}
